"use client";

import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type CourtLabel = {
  court_number: number;
  label: string;
};

type MatchmakingProfile = {
  id: string;
  name: string;
};

type AutoGenerateDialogProps = {
  open: boolean;
  onClose: () => void;
  availableCourts: number[];
  courtLabels: CourtLabel[];
  profiles: MatchmakingProfile[];
  defaultProfileId: string | null;
  onGenerate: (selectedCourts: number[], profileId: string) => void;
};

function getCourtName(num: number, labels: CourtLabel[]): string {
  return labels.find((l) => l.court_number === num)?.label ?? `Court ${num}`;
}

export function AutoGenerateDialog({
  open,
  onClose,
  availableCourts,
  courtLabels,
  profiles,
  defaultProfileId,
  onGenerate,
}: AutoGenerateDialogProps) {
  const [selectedCourts, setSelectedCourts] = useState<Set<number>>(
    new Set(availableCourts)
  );
  const [selectedProfileId, setSelectedProfileId] = useState<string>(
    defaultProfileId ?? profiles[0]?.id ?? ""
  );

  // Reset to current available courts and default profile each time the dialog opens.
  useEffect(() => {
    if (!open) return;
    setSelectedCourts(new Set(availableCourts));
    setSelectedProfileId(defaultProfileId ?? profiles[0]?.id ?? "");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  function toggleCourt(court: number) {
    setSelectedCourts((prev) => {
      const next = new Set(prev);
      if (next.has(court)) {
        next.delete(court);
      } else {
        next.add(court);
      }
      return next;
    });
  }

  const canGenerate = selectedCourts.size > 0 && selectedProfileId !== "";

  function handleGenerate() {
    if (!canGenerate) return;
    onGenerate(Array.from(selectedCourts).sort((a, b) => a - b), selectedProfileId);
  }

  function handleOpenChange(isOpen: boolean) {
    if (!isOpen) onClose();
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle>Auto Generate Matches</DialogTitle>
        </DialogHeader>

        <div className="space-y-5">
          {/* Court selection */}
          <div className="space-y-2">
            <p className="text-sm font-medium">Courts</p>
            {availableCourts.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No available courts.
              </p>
            ) : (
              <div className="space-y-2">
                {availableCourts.map((court) => (
                  <div key={court} className="flex items-center gap-3">
                    <Checkbox
                      id={`court-${court}`}
                      checked={selectedCourts.has(court)}
                      onCheckedChange={() => toggleCourt(court)}
                    />
                    <Label
                      htmlFor={`court-${court}`}
                      className="cursor-pointer font-normal"
                    >
                      {getCourtName(court, courtLabels)}
                    </Label>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Profile selection */}
          <div className="space-y-2">
            <p className="text-sm font-medium">Matchmaking Profile</p>
            {profiles.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No profiles available.
              </p>
            ) : (
              <Select
                value={selectedProfileId}
                onValueChange={setSelectedProfileId}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select a profile" />
                </SelectTrigger>
                <SelectContent>
                  {profiles.map((profile) => (
                    <SelectItem key={profile.id} value={profile.id}>
                      {profile.name}
                      {profile.id === defaultProfileId && (
                        <span className="ml-1.5 text-xs text-muted-foreground">
                          (default)
                        </span>
                      )}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => handleOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleGenerate} disabled={!canGenerate}>
            Generate
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
